#pragma once
#include <string>
#include <fstream>

inline void write_smt_file(const std::string& path, const std::string& body)
{
    std::ofstream out(path);
    out << "; auto-generated by Symbolic Engine\n"
        << "(set-logic ALL)\n"
        << body;
}
