#ifndef SMTLIB_PRINTER_HPP
#define SMTLIB_PRINTER_HPP

#include <ostream>
#include <sstream>
#include <fstream>
#include <unordered_map>
#include "ast.hpp"
#include "SymbolicEnv.hpp"

/* tiny helper – occasionally handy in ad-hoc tests */
inline void write_smt_file(const std::string& path,
                           const std::string& body)
{
    std::ofstream out(path);
    out << "; auto-generated by Symbolic Engine\n"
        << "(set-logic ALL)\n"
        << body;
}

/*==========================================================================*/
/*  Expr → SMT-LIB  (all helpers lowered; tolerant on in(x,"lit"))          */
/*==========================================================================*/
namespace {

static inline bool isTrueLiteral (const std::string& s){ return s=="true";  }
static inline bool isFalseLiteral(const std::string& s){ return s=="false"; }

static std::string smtOf(SymbolicEnv& sigma, const Expr& expr)
{
    struct V : ASTVisitor
    {
        explicit V(SymbolicEnv& sig) : sigma(sig) {}

        SymbolicEnv&       sigma;
        std::ostringstream out;

        /* convenience */
        std::string sub(const Expr& e) { V t(sigma); const_cast<Expr&>(e).accept(t); return t.out.str(); }

        /*──────────────────── leaves ────────────────────*/
        void visit(const Var& n)      override {
            if (n.name=="true" || n.name=="false") { out << n.name; return; }
            out << sigma.symFor(n.name);
        }
        void visit(const Num& n)      override { out << n.value; }
        void visit(const String& n)   override { out << '"' << n.value << '"'; }

        /*──────────────────── helpers / calls ───────────*/
        void visit(const FuncCall& n) override
        {
            /* 0 ─ boolean constants: true()/false() */
            if ((n.name=="true" || n.name=="false") && n.args.empty())
            { out << n.name; return; }

            /* 1 ─ input() / input(x)  → brand-new symbol */
            if (n.name=="input" && (n.args.size()==0 || n.args.size()==1))
            { out << sigma.freshSym("inp"); return; }

            /* 2 ─ equals/boolEq(a,b)  → (= a b) */
            if ((n.name=="equals" || n.name=="boolEq") && n.args.size()==2)
            { out << "(= " << sub(*n.args[0]) << ' ' << sub(*n.args[1]) << ')'; return; }

            /* 3 ─ not / not1 */
            if ((n.name=="not" || n.name=="not1") && n.args.size()==1) {
                std::string x = sub(*n.args[0]);
                if (isTrueLiteral(x))  { out << "false"; return; }
                if (isFalseLiteral(x)) { out << "true";  return; }
                out << "(not " << x << ')'; return;
            }

            /* 4 ─ is_true / is_false – wrappers */
            if (n.name=="is_true"  && n.args.size()==1)
            { out << sub(*n.args[0]); return; }
            if (n.name=="is_false" && n.args.size()==1)
            { out << "(not " << sub(*n.args[0]) << ')'; return; }

            /* 5 ─ and_operator / and2(e1…en) → (and …) */
            if ((n.name=="and_operator" || n.name=="and2") && !n.args.empty()) {
                std::vector<std::string> parts; parts.reserve(n.args.size());
                for (auto& a : n.args) {
                    std::string t = sub(*a);
                    if (isFalseLiteral(t)) { out << "false"; return; }
                    if (!isTrueLiteral(t)) parts.push_back(std::move(t));
                }
                if (parts.empty())     { out << "true";  return; }
                if (parts.size()==1)   { out << parts[0]; return; }
                out << "(and"; for (auto& p : parts) out << ' ' << p; out << ')'; return;
            }

            /* 6 ─ or_operator / or2(e1…en) → (or …) */
            if ((n.name=="or_operator" || n.name=="or2") && !n.args.empty()) {
                std::vector<std::string> parts; parts.reserve(n.args.size());
                for (auto& a : n.args) {
                    std::string t = sub(*a);
                    if (isTrueLiteral(t))  { out << "true"; return; }
                    if (!isFalseLiteral(t)) parts.push_back(std::move(t));
                }
                if (parts.empty())     { out << "false"; return; }
                if (parts.size()==1)   { out << parts[0]; return; }
                out << "(or"; for (auto& p : parts) out << ' ' << p; out << ')'; return;
            }

            /* 7 ─ getMapAtMatch(u,p) – invent synthetic map */
            if (n.name=="getMapAtMatch" && n.args.size()==2) {
                static std::unordered_map<const FuncCall*,std::string> memo;
                static int                                           cnt = 0;

                auto it = memo.find(&n);
                if (it==memo.end()) {
                    it = memo.emplace(&n, "Match" + std::to_string(++cnt)).first;
                    sigma.declareMap(it->second);             // Dom_/Val_
                }
                out << it->second;                            // base id
                return;
            }

            /* 8 ─ dom(M)  – var *or* getMapAtMatch(...) */
            if (n.name=="dom" && n.args.size()==1) {
                const Expr& arg = *n.args[0];

                /* plain variable */
                if (auto* v = dynamic_cast<const Var*>(&arg)) {
                    if (!sigma.isMap(v->name)) sigma.declareMap(v->name);
                    out << sigma.getMap(v->name).dom;
                    return;
                }

                /* getMapAtMatch(...)  */
                if (auto* gm = dynamic_cast<const FuncCall*>(&arg);
                    gm && gm->name=="getMapAtMatch")
                {
                    out << sigma.getMap(sub(arg)).dom;   // sub(arg) == base-id
                    return;
                }
            }

            /* 9 ─ in_dom(M,k) */
            if (n.name=="in_dom" && n.args.size()==2) {
                const Expr& m = *n.args[0];
                const Expr& k = *n.args[1];

                auto mapBaseFromExpr = [&](const Expr& me) -> std::string {
                    if (auto* v = dynamic_cast<const Var*>(&me)) {
                        if (!sigma.isMap(v->name)) sigma.declareMap(v->name);
                        return v->name;
                    }
                    if (auto* gm = dynamic_cast<const FuncCall*>(&me)) {
                        if (gm->name=="getMapAtMatch") {
                            std::string id = sub(me);
                            if (!sigma.isMap(id)) sigma.declareMap(id);
                            return id;
                        }
                    }
                    return {};
                };

                std::string base = mapBaseFromExpr(m);
                if (!base.empty()) {
                    out << "(select " << sigma.getMap(base).dom
                        << ' ' << sub(k) << ')';
                    return;
                }
            }

            /* 10 ─ not_in(...)  (M may be Var or getMapAtMatch) */
            if (n.name=="not_in" && n.args.size()==2) {
                auto mapBaseFromExpr = [&](const Expr& me) -> std::string {
                    if (auto* v = dynamic_cast<const Var*>(&me)) {
                        if (!sigma.isMap(v->name)) sigma.declareMap(v->name);
                        return v->name;
                    }
                    if (auto* gm = dynamic_cast<const FuncCall*>(&me)) {
                        if (gm->name=="getMapAtMatch") {
                            std::string id = sub(me);
                            if (!sigma.isMap(id)) sigma.declareMap(id);
                            return id;
                        }
                    }
                    return {};
                };

                std::string base; const Expr* key = nullptr;

                if (auto* dom = dynamic_cast<const FuncCall*>(n.args[1].get());
                    dom && dom->name=="dom" && dom->args.size()==1)
                { base = mapBaseFromExpr(*dom->args[0]); key = n.args[0].get(); }

                if (base.empty())
                { base = mapBaseFromExpr(*n.args[0]); key = n.args[1].get(); }

                if (!base.empty()) {
                    out << "(not (select " << sigma.getMap(base).dom
                        << ' ' << sub(*key) << "))";
                    return;
                }
            }

            /* 11 ─ mapped_value / mapVal (M,k) */
            if ((n.name=="mapped_value" || n.name=="mapVal") && n.args.size()==2) {
                auto mapBaseFromExpr = [&](const Expr& me) -> std::string {
                    if (auto* v = dynamic_cast<const Var*>(&me)) {
                        if (!sigma.isMap(v->name)) sigma.declareMap(v->name);
                        return v->name;
                    }
                    if (auto* gm = dynamic_cast<const FuncCall*>(&me)) {
                        if (gm->name=="getMapAtMatch") {
                            std::string id = sub(me);
                            if (!sigma.isMap(id)) sigma.declareMap(id);
                            return id;
                        }
                    }
                    return {};
                };
                std::string base = mapBaseFromExpr(*n.args[0]);
                if (!base.empty()) {
                    out << "(select " << sigma.getMap(base).val
                        << ' ' << sub(*n.args[1]) << ')';
                    return;
                }
            }

            /* 12 ─ in(k, Dom) / tolerant singleton */
            if (n.name=="in" && n.args.size()==2) {
                if (dynamic_cast<const String*>(n.args[1].get())) {
                    sigma.addWarning("lowered in(x, \"lit\") to (= x \"lit\")");
                    out << "(= " << sub(*n.args[0]) << ' ' << sub(*n.args[1]) << ')';
                    return;
                }
                out << "(select " << sub(*n.args[1]) << ' ' << sub(*n.args[0]) << ')';
                return;
            }

            /* default: uninterpreted application (rare at this point) */
            out << '(' << n.name;
            for (auto& a : n.args) { out << ' ' << sub(*a); }
            out << ')';
        }

        /*──────────── stub everything else so V becomes concrete ───────────*/
        void visit(const Assign&)       override {}
        void visit(const FuncCallStmt&) override {}
        void visit(const Program&)      override {}
        void visit(const Decl&)         override {}
        void visit(const FuncDecl&)     override {}
        void visit(const APIcall&)      override {}
        void visit(const API&)          override {}
        void visit(const Response&)     override {}
        void visit(const Init&)         override {}
        void visit(const Spec&)         override {}
        void visit(const Set&)          override {}
        void visit(const Map&)          override {}
        void visit(const Tuple&)        override {}
        void visit(const TypeConst&)    override {}
        void visit(const FuncType&)     override {}
        void visit(const MapType&)      override {}
        void visit(const TupleType&)    override {}
        void visit(const SetType&)      override {}
    };

    V v(sigma);
    const_cast<Expr&>(expr).accept(v);
    return v.out.str();
}

} // anonymous namespace
#endif /* SMTLIB_PRINTER_HPP */
